import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "./reduxTolkit/provider";
import TanstackProvider from "@/Providers/TanstackProvider";
import { Provider } from "@/components/ui/provider";

export const metadata: Metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <TanstackProvider>
            <Provider>{children}</Provider>
          </TanstackProvider>
        </body>
      </html>
    </Providers>
  );
}
